version: "3"

services:

  webapp:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DB_URL: jdbc:postgresql://db/apps
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db
    ports:
      - "8080:8080"
    expose:
      - "8080"

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: apps
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
