---
spring:
  application:
    name: apps-app
  datasource:
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jackson:
    default-property-inclusion: NON_NULL

logging:
  level:
    net:
      uiqui:
        load: ${LOGGING_LEVEL:info}